package eu.ksiegowasowa.swing;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import eu.ksiegowasowa.convert.ConvertException;
import eu.ksiegowasowa.convert.FileConverter;

public class ApplicationFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 3872726742859874947L;

	private JLabel fileNameLabel;
	private JButton selectFileButton;
	private JButton convertButton;
	private JFileChooser fileChooser;

	public ApplicationFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		fileNameLabel = new JLabel();
		convertButton = new JButton();
		selectFileButton = new JButton();
		fileChooser = new JFileChooser();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("2 Optima Konwerter");

		fileNameLabel.setText("");

		convertButton.setText("Konwertuj");
		convertButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				convertButtonActionPerformed(evt);
			}
		});
		selectFileButton.setText("Wybierz plik");
		selectFileButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectFileActionPerformed(evt);
			}
		});
		selectFileButton.setSize(50, 20);
		setSize(350, 150);		
		
		centreWindow(this);
		GridLayout layout = new GridLayout(3, 1);
		Container myPanel = getContentPane();
		myPanel.setLayout(layout);
		myPanel.add(selectFileButton);
		myPanel.add(fileNameLabel);
		myPanel.add(convertButton);

	}

	private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_convertButtonActionPerformed
		// do conversion
		if (!fileNameLabel.getText().isEmpty()) {
			String message = "Gotowe!";
			FileConverter fc = new FileConverter();
			try {
				fc.convert(fileNameLabel.getText());
			} catch (ConvertException e) {
				message = e.getMessage();
			}
			JOptionPane.showMessageDialog(this, message);
		} else {
			JOptionPane.showMessageDialog(this, "Nie wybrano pliku");
		}
	}
	
	private void selectFileActionPerformed(ActionEvent evt) {
		int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            fileNameLabel.setText(file.getAbsolutePath());
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getAbsolutePath());
            
        } else {
        	fileNameLabel.setText("");
            System.out.println("Open command cancelled by user.");
        }
	}
	
	private void centreWindow(Window frame) {
	    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
	    int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
	    int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
	    frame.setLocation(x, y);
	}	

}
